/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.OxygenPlant.OxygenPlant;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nithin Bharadwaj
 */
public class ManageOxygenPlantDetails extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomerDetails
     */
    JPanel userProcessContainer;
    EcoSystem system;
    
    public ManageOxygenPlantDetails(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurants = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lbPassword = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtRestaurantName = new javax.swing.JTextField();
        lbRestaurant = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lbPassword1 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 252, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Manage Oxygen Plants");
        add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 420, 44));

        tblRestaurants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Plant Name", "Admin Name", "Username", "PhoneNumber", "Address"
            }
        ));
        jScrollPane1.setViewportView(tblRestaurants);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 141, 496, 96));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 255, 65, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 255, -1, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 384, 159, -1));

        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 516, -1, -1));

        lbPassword.setText("Phone Number :");
        add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 433, -1, -1));

        lbName.setText("Admin Name :");
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 340, 159, -1));

        lbUsername.setText("Username :");
        add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 36, 60, 60));
        add(txtRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 296, 159, -1));

        lbRestaurant.setText("Plant Name :");
        add(lbRestaurant, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 428, 159, -1));

        lbPassword1.setText("Address :");
        add(lbPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 477, -1, -1));

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 472, 159, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/giffing.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 480, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof SystemAdminWorkAreaJPanel){
                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                systemAdminWorkAreaJPanel.populateTree();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblRestaurants.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        OxygenPlant selectedRestaurant = (OxygenPlant)model.getValueAt(selectedRowIndex, 0);

        String name = txtName.getText();
        String plantName = txtRestaurantName.getText();
        String userName = txtUsername.getText();
        long phoneNumber = Long.parseLong(txtPhoneNumber.getText());
        String address = txtAddress.getText();
        
        ArrayList<OxygenPlant> restos = system.getOxygenPlantDirectory().returnAllOxygenPlants();
        for(OxygenPlant r: restos)
        {
            if(r.getManagerName().equals(selectedRestaurant.getManagerName()))
            {
               r.returnUserAcc().setUsername(userName);
               r.setManagerName(name);
               r.setOxygenPlantName(plantName);
               r.setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
               r.setAddress(txtAddress.getText());
               break;
            }
            
        }
        system.setRestaurantDirectory(restos);
        JOptionPane.showMessageDialog(this, "Updated the details successfully");
        txtName.setText("");txtUsername.setText("");txtRestaurantName.setText("");
        txtAddress.setText("");txtPhoneNumber.setText("");
        populateTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
          int selectedRowIndex = tblRestaurants.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        OxygenPlant selectedRestaurant = (OxygenPlant)model.getValueAt(selectedRowIndex, 0);
        txtName.setText("");
        txtName.setText(selectedRestaurant.getManagerName());
        txtUsername.setText("");
        txtUsername.setText(selectedRestaurant.returnUserAcc().getUsername());
        txtRestaurantName.setText("");
        txtRestaurantName.setText(selectedRestaurant.getOxygenPlantName());
        txtAddress.setText("");
        txtAddress.setText(selectedRestaurant.getAddress());
        txtPhoneNumber.setText("");
        txtPhoneNumber.setText(String.valueOf(selectedRestaurant.getPhoneNumber()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblRestaurants.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        OxygenPlant selectedRestaurant = (OxygenPlant)model.getValueAt(selectedRowIndex, 0);
        // First delete the customer from employee
        this.system.getEmployeeDirectory().deleteEmployee(selectedRestaurant.getManagerName());
        // And thne delete the userAccount
        this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getOxygenPlantDirectory().returnAllOxygenPlants().
                        get(selectedRowIndex).returnUserAcc()
        );
        // finally delete the user from customer directory
        this.system.getOxygenPlantDirectory().removeOxygenPlant(selectedRestaurant);
        
        JOptionPane.showMessageDialog(this, "Deleted the restaurant Successfully");
        for(Customer ck : this.system.getCustomerDirectory().returnCustomerDetails()){
            System.out.println(ck.getName());
        }
        this.populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPassword1;
    private javax.swing.JLabel lbRestaurant;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tblRestaurants;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populateTable(){
        System.out.println("Inside method to populate Restaurant details table");
        DefaultTableModel model = (DefaultTableModel) tblRestaurants.getModel();
        model.setRowCount(0);

        for(OxygenPlant rest : this.system.getOxygenPlantDirectory().returnAllOxygenPlants()){
            System.out.println(rest);
            Object[] row = new Object[5];
            row[0] = rest;
            row[1] = rest.getManagerName();
            row[2] = rest.returnUserAcc().getUsername();
            row[3] = String.valueOf(rest.getPhoneNumber());
            row[4] = rest.getAddress();
            model.addRow(row);
        }
    }

}
