/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.AviationOrg.AviationOrg;
import Business.AviationOrg.AviationOrgAdmin;
import Business.Customer.Customer;
import Business.DefenseOrg.DefenseOrg;
import Business.DefenseOrg.DefenseOrgAdmin;
import Business.EcoSystem;
import Business.Hospital.Hospital;
import Business.Hospital.HospitalAdmin;
import Business.PharmaOrg.PharmaOrg;
import Business.PharmaOrg.PharmaOrgAdmin;
import Business.ScubaOrg.ScubaOrg;
import Business.ScubaOrg.ScubaOrgAdmin;
import Business.WaterDepartment.WaterTreatmentOrg;
import Business.WaterDepartment.WaterTreatmentOrgAdmin;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nithin Bharadwaj
 */
public class ManageBussinessAdmin extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomerDetails
     */
    JPanel userProcessContainer;
    EcoSystem system;
    
    public ManageBussinessAdmin(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerDetails = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lbPassword = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        lbPassword1 = new javax.swing.JLabel();
        lbPassword2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        comboRole = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 252, 255));

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Manage Business Admin Details");

        tblCustomerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "UserName", "Password", "Address", "PhoneNumber", "Business Name"
            }
        ));
        jScrollPane1.setViewportView(tblCustomerDetails);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });

        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        lbPassword.setText("Password :");

        lbName.setText("Name :");

        lbUsername.setText("Username :");

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lbPassword1.setText("Address :");

        lbPassword2.setText("Phone Number :");

        comboRole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pharma Admin", "Defense Manager", "Aviation Manager", "Scuba Manager", "WaterPlant Admin" }));
        comboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Role :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lbUsername)
                                            .addComponent(lbName))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPassword2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPassword)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbPassword1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(66, 66, 66)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitle)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnView)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPassword2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSubmit)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof SystemAdminWorkAreaJPanel){
                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                systemAdminWorkAreaJPanel.populateTree();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCustomerDetails.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        String roleSelected = comboRole.getSelectedItem().toString();
        if(roleSelected == "Pharma Admin"){
            PharmaOrgAdmin selectedCustomer = (PharmaOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            String name = txtName.getText();
            String userName = txtUsername.getText();
            String password = txtpassword.getText();
            
            ArrayList<PharmaOrg> restos = this.system.getPharmaDirectory().returnAllPharmaBusinesss();
            for(PharmaOrg r: restos)
            {
                if(r.getBusinessAdmin().getName().equals(selectedCustomer.getName()))
                {
                    r.getBusinessAdmin().setName(name);
                    r.getBusinessAdmin().returnUserAccount().setUsername(userName);
                    r.getBusinessAdmin().returnUserAccount().setPassword(password);
                    r.getBusinessAdmin().setUserName(userName);
                    r.getBusinessAdmin().setUserPassword(password);
                    r.getBusinessAdmin().setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                    r.getBusinessAdmin().setAddress(txtAddress.getText());
                    break;
                }

            }
            this.system.setPharmaOrgDirectory(restos);
            JOptionPane.showMessageDialog(this, "Updated Successfully");

            txtName.setText("");txtUsername.setText("");txtpassword.setText("");
            txtAddress.setText("");txtPhoneNumber.setText("");
            populateTable("Pharma Admin");
        }
        else if(roleSelected == "Defense Manager"){
            DefenseOrgAdmin selectedCustomer = (DefenseOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            String name = txtName.getText();
            String userName = txtUsername.getText();
            String password = txtpassword.getText();
            
            ArrayList<DefenseOrg> restos = this.system.getDefenseDirectory().returnAllDefenseBusinesses();
            for(DefenseOrg r: restos)
            {
                if(r.getBusinessAdmin().getName().equals(selectedCustomer.getName()))
                {
                    r.getBusinessAdmin().setName(name);
                    r.getBusinessAdmin().returnUserAccount().setUsername(userName);
                    r.getBusinessAdmin().returnUserAccount().setPassword(password);
                    r.getBusinessAdmin().setUserName(userName);
                    r.getBusinessAdmin().setUserPassword(password);
                    r.getBusinessAdmin().setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                    r.getBusinessAdmin().setAddress(txtAddress.getText());
                    break;
                }

            }
            this.system.setDefenseOrgDirectory(restos);
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            txtName.setText("");txtUsername.setText("");txtpassword.setText("");
            txtAddress.setText("");txtPhoneNumber.setText("");
            populateTable("Defense Manager");
        }
        else if(roleSelected == "Aviation Manager"){
            AviationOrgAdmin selectedCustomer = (AviationOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            String name = txtName.getText();
            String userName = txtUsername.getText();
            String password = txtpassword.getText();
            
            ArrayList<AviationOrg> restos = this.system.getAviationDirectory().returnAllAviationBusinesss();
            for(AviationOrg r: restos)
            {
                if(r.getBusinessAdmin().getName().equals(selectedCustomer.getName()))
                {
                    r.getBusinessAdmin().setName(name);
                    r.getBusinessAdmin().returnUserAccount().setUsername(userName);
                    r.getBusinessAdmin().returnUserAccount().setPassword(password);
                    r.getBusinessAdmin().setUserName(userName);
                    r.getBusinessAdmin().setUserPassword(password);
                    r.getBusinessAdmin().setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                    r.getBusinessAdmin().setAddress(txtAddress.getText());
                    break;
                }

            }
            this.system.setAviationOrgDirectory(restos);
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            txtName.setText("");txtUsername.setText("");txtpassword.setText("");
            txtAddress.setText("");txtPhoneNumber.setText("");
            populateTable("Aviation Manager");        
        }
        else if(roleSelected == "Scuba Manager"){
            ScubaOrgAdmin selectedCustomer = (ScubaOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            String name = txtName.getText();
            String userName = txtUsername.getText();
            String password = txtpassword.getText();
            
            ArrayList<ScubaOrg> restos = this.system.getScubaOrgDirectory().returnAllScubaBusinesses();
            for(ScubaOrg r: restos)
            {
                if(r.getBusinessAdmin().getName().equals(selectedCustomer.getName()))
                {
                    r.getBusinessAdmin().setName(name);
                    r.getBusinessAdmin().returnUserAccount().setUsername(userName);
                    r.getBusinessAdmin().returnUserAccount().setPassword(password);
                    r.getBusinessAdmin().setUserName(userName);
                    r.getBusinessAdmin().setUserPassword(password);
                    r.getBusinessAdmin().setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                    r.getBusinessAdmin().setAddress(txtAddress.getText());
                    break;
                }

            }
            this.system.setScubaOrgDirectory(restos);
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            txtName.setText("");txtUsername.setText("");txtpassword.setText("");
            txtAddress.setText("");txtPhoneNumber.setText("");
            populateTable("Scuba Manager");
        }
        else if(roleSelected == "WaterPlant Admin"){
            WaterTreatmentOrgAdmin selectedCustomer = (WaterTreatmentOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            String name = txtName.getText();
            String userName = txtUsername.getText();
            String password = txtpassword.getText();
            
            ArrayList<WaterTreatmentOrg> restos = this.system.getWaterTreatementirectory().returnAllWaterTreatmentBusinesses();
            for(WaterTreatmentOrg r: restos)
            {
                if(r.getBusinessAdmin().getName().equals(selectedCustomer.getName()))
                {
                    r.getBusinessAdmin().setName(name);
                    r.getBusinessAdmin().returnUserAccount().setUsername(userName);
                    r.getBusinessAdmin().returnUserAccount().setPassword(password);
                    r.getBusinessAdmin().setUserName(userName);
                    r.getBusinessAdmin().setUserPassword(password);
                    r.getBusinessAdmin().setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                    r.getBusinessAdmin().setAddress(txtAddress.getText());
                    break;
                }

            }
            this.system.setWaterTreatementOrgDirectory(restos);
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            txtName.setText("");txtUsername.setText("");txtpassword.setText("");
            txtAddress.setText("");txtPhoneNumber.setText("");
            populateTable("WaterPlant Admin");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        String roleSelected = comboRole.getSelectedItem().toString();
        int selectedRowIndex = tblCustomerDetails.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        if(roleSelected == "Pharma Admin"){
            PharmaOrgAdmin selectedCustomer = (PharmaOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            txtName.setText("");
            txtName.setText(selectedCustomer.getName());
            txtUsername.setText("");
            txtUsername.setText(selectedCustomer.getUserName());
            txtpassword.setText("");
            txtpassword.setText(selectedCustomer.getUserPassword());
            txtAddress.setText("");
            txtAddress.setText(selectedCustomer.getAddress());
            txtPhoneNumber.setText("");
            txtPhoneNumber.setText(String.valueOf(selectedCustomer.getPhoneNumber()));
        }
        else if(roleSelected == "Defense Manager"){
            DefenseOrgAdmin selectedCustomer = (DefenseOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            txtName.setText("");
            txtName.setText(selectedCustomer.getName());
            txtUsername.setText("");
            txtUsername.setText(selectedCustomer.getUserName());
            txtpassword.setText("");
            txtpassword.setText(selectedCustomer.getUserPassword());
            txtAddress.setText("");
            txtAddress.setText(selectedCustomer.getAddress());
            txtPhoneNumber.setText("");
            txtPhoneNumber.setText(String.valueOf(selectedCustomer.getPhoneNumber()));
        }
        else if(roleSelected == "Aviation Manager"){
            AviationOrgAdmin selectedCustomer = (AviationOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            txtName.setText("");
            txtName.setText(selectedCustomer.getName());
            txtUsername.setText("");
            txtUsername.setText(selectedCustomer.getUserName());
            txtpassword.setText("");
            txtpassword.setText(selectedCustomer.getUserPassword());
            txtAddress.setText("");
            txtAddress.setText(selectedCustomer.getAddress());
            txtPhoneNumber.setText("");
            txtPhoneNumber.setText(String.valueOf(selectedCustomer.getPhoneNumber()));
        }
        else if(roleSelected == "Scuba Manager"){
            ScubaOrgAdmin selectedCustomer = (ScubaOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            txtName.setText("");
            txtName.setText(selectedCustomer.getName());
            txtUsername.setText("");
            txtUsername.setText(selectedCustomer.getUserName());
            txtpassword.setText("");
            txtpassword.setText(selectedCustomer.getUserPassword());
            txtAddress.setText("");
            txtAddress.setText(selectedCustomer.getAddress());
            txtPhoneNumber.setText("");
            txtPhoneNumber.setText(String.valueOf(selectedCustomer.getPhoneNumber()));
        }
        else{
            WaterTreatmentOrgAdmin selectedCustomer = (WaterTreatmentOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            txtName.setText("");
            txtName.setText(selectedCustomer.getName());
            txtUsername.setText("");
            txtUsername.setText(selectedCustomer.getUserName());
            txtpassword.setText("");
            txtpassword.setText(selectedCustomer.getUserPassword());
            txtAddress.setText("");
            txtAddress.setText(selectedCustomer.getAddress());
            txtPhoneNumber.setText("");
            txtPhoneNumber.setText(String.valueOf(selectedCustomer.getPhoneNumber()));
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCustomerDetails.getSelectedRow();
        String roleSelected = comboRole.getSelectedItem().toString();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        if(roleSelected == "Pharma Admin"){
            PharmaOrgAdmin selectedCustomer = (PharmaOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            // First delete the customer from employee
            this.system.getEmployeeDirectory().deleteEmployee(selectedCustomer.getName());
            // And thne delete the userAccount
            this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getPharmaDirectory().returnAllPharmaBusinesss().
                        get(selectedRowIndex).getBusinessAdmin().returnUserAccount()
            );
            // finally delete the user from customer directory
            ArrayList<PharmaOrg> pharmaList = system.getPharmaDirectory().returnAllPharmaBusinesss();

            for(PharmaOrg pO : pharmaList){
                if(pO.getBusinessAdmin().getName().equals(selectedCustomer.getName())){
                    pO.setBusinessAdmin(null);break;
                }
            }
            this.system.setPharmaOrgDirectory(pharmaList);
            this.populateTable("Pharma Admin");
        }
        else if(roleSelected == "Defense Manager"){
            DefenseOrgAdmin selectedCustomer = (DefenseOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            // First delete the customer from employee
            this.system.getEmployeeDirectory().deleteEmployee(selectedCustomer.getName());
            // And thne delete the userAccount
            this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getDefenseDirectory().returnAllDefenseBusinesses().
                        get(selectedRowIndex).getBusinessAdmin().returnUserAccount()
            );
            // finally delete the user from customer directory
            ArrayList<DefenseOrg> defenseList = system.getDefenseDirectory().returnAllDefenseBusinesses();

            for(DefenseOrg pO : defenseList){
                if(pO.getBusinessAdmin().getName().equals(selectedCustomer.getName())){
                    pO.setBusinessAdmin(null);break;
                }
            }
            this.system.setDefenseOrgDirectory(defenseList);
            this.populateTable("Defense Manager");
        }
        else if(roleSelected == "Aviation Manager"){
            AviationOrgAdmin selectedCustomer = (AviationOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            // First delete the customer from employee
            this.system.getEmployeeDirectory().deleteEmployee(selectedCustomer.getName());
            // And thne delete the userAccount
            this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getAviationDirectory().returnAllAviationBusinesss().
                        get(selectedRowIndex).getBusinessAdmin().returnUserAccount()
            );
            // finally delete the user from customer directory
            ArrayList<AviationOrg> aviationList = system.getAviationDirectory().returnAllAviationBusinesss();

            for(AviationOrg pO : aviationList){
                if(pO.getBusinessAdmin().getName().equals(selectedCustomer.getName())){
                    pO.setBusinessAdmin(null);break;
                }
            }
            this.system.setAviationOrgDirectory(aviationList);
            this.populateTable("Aviation Manager");
        
        }else if(roleSelected == "Scuba Manager"){
            ScubaOrgAdmin selectedCustomer = (ScubaOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            // First delete the customer from employee
            this.system.getEmployeeDirectory().deleteEmployee(selectedCustomer.getName());
            // And thne delete the userAccount
            this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getScubaOrgDirectory().returnAllScubaBusinesses().
                        get(selectedRowIndex).getBusinessAdmin().returnUserAccount()
            );
            // finally delete the user from customer directory
            ArrayList<ScubaOrg> scubaList = system.getScubaOrgDirectory().returnAllScubaBusinesses();

            for(ScubaOrg pO : scubaList){
                if(pO.getBusinessAdmin().getName().equals(selectedCustomer.getName())){
                    pO.setBusinessAdmin(null);break;
                }
            }
            this.system.setScubaOrgDirectory(scubaList);      
            this.populateTable("Scuba Manager");
        
        }else if(roleSelected == "WaterPlant Admin"){
            WaterTreatmentOrgAdmin selectedCustomer = (WaterTreatmentOrgAdmin)model.getValueAt(selectedRowIndex, 0);
            // First delete the customer from employee
            this.system.getEmployeeDirectory().deleteEmployee(selectedCustomer.getName());
            // And thne delete the userAccount
            this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getWaterTreatementirectory().returnAllWaterTreatmentBusinesses().
                        get(selectedRowIndex).getBusinessAdmin().returnUserAccount()
            );
            // finally delete the user from customer directory
            ArrayList<WaterTreatmentOrg> scubaList = system.getWaterTreatementirectory().returnAllWaterTreatmentBusinesses();

            for(WaterTreatmentOrg pO : scubaList){
                if(pO.getBusinessAdmin().getName().equals(selectedCustomer.getName())){
                    pO.setBusinessAdmin(null);break;
                }
            }
            this.system.setWaterTreatementOrgDirectory(scubaList);
            this.populateTable("WaterPlant Admin");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void comboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoleActionPerformed
        // TODO add your handling code here:
        System.out.println("Selected Role : " + comboRole.getSelectedItem().toString());
        if(comboRole.getSelectedItem().toString().equals("Pharma Admin")){
            populateTable("Pharma Admin");
        }
        else if(comboRole.getSelectedItem().toString().equals("Defense Manager")){
            populateTable("Defense Manager");
        }
        else if(comboRole.getSelectedItem().toString().equals("Aviation Manager")){
            populateTable("Aviation Manager");
        }
        else if(comboRole.getSelectedItem().toString().equals("Scuba Manager")){
            populateTable("Scuba Manager");
        }
        else if(comboRole.getSelectedItem().toString().equals("WaterPlant Admin")){
            populateTable("WaterPlant Admin");
        }
    }//GEN-LAST:event_comboRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox comboRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPassword1;
    private javax.swing.JLabel lbPassword2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tblCustomerDetails;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    private void populateTable(String roleName){
        System.out.println("Inside method to populate Customer table");
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        model.setRowCount(0);
        try{
            if(roleName == "Pharma Admin"){
                for(PharmaOrg cust : this.system.getPharmaDirectory().returnAllPharmaBusinesss()){
//                    System.out.println(cust.getHospitalAdmin());
                    Object[] row = new Object[6];
                    row[0] = cust.getBusinessAdmin();
                    row[1] = cust.getBusinessAdmin().getUserName();
                    row[2] = cust.getBusinessAdmin().getUserPassword();
                    row[3] = cust.getBusinessAdmin().getAddress();
                    row[4] = cust.getBusinessAdmin().getPhoneNumber();
                    row[5] = cust.getBusinessName();
                    model.addRow(row);
                    }
            }
            else if(roleName == "Defense Manager"){
                for(DefenseOrg cust : this.system.getDefenseDirectory().returnAllDefenseBusinesses()){
//                    System.out.println(cust.getHospitalAdmin());
                    Object[] row = new Object[6];
                    row[0] = cust.getBusinessAdmin();
                    row[1] = cust.getBusinessAdmin().getUserName();
                    row[2] = cust.getBusinessAdmin().getUserPassword();
                    row[3] = cust.getBusinessAdmin().getAddress();
                    row[4] = cust.getBusinessAdmin().getPhoneNumber();
                    row[5] = cust.getBusinessName();
                    model.addRow(row);
                    }
            }
            else if(roleName == "Aviation Manager"){
                for(AviationOrg cust : this.system.getAviationDirectory().returnAllAviationBusinesss()){
//                    System.out.println(cust.getHospitalAdmin());
                    Object[] row = new Object[6];
                    row[0] = cust.getBusinessAdmin();
                    row[1] = cust.getBusinessAdmin().getUserName();
                    row[2] = cust.getBusinessAdmin().getUserPassword();
                    row[3] = cust.getBusinessAdmin().getAddress();
                    row[4] = cust.getBusinessAdmin().getPhoneNumber();
                    row[5] = cust.getBusinessName();
                    model.addRow(row);
                    }
            }
            else if(roleName == "Scuba Manager"){
                for(ScubaOrg cust : this.system.getScubaOrgDirectory().returnAllScubaBusinesses()){
//                    System.out.println(cust.getHospitalAdmin());
                    Object[] row = new Object[6];
                    row[0] = cust.getBusinessAdmin();
                    row[1] = cust.getBusinessAdmin().getUserName();
                    row[2] = cust.getBusinessAdmin().getUserPassword();
                    row[3] = cust.getBusinessAdmin().getAddress();
                    row[4] = cust.getBusinessAdmin().getPhoneNumber();
                    row[5] = cust.getBusinessName();
                    model.addRow(row);
                    }
            }
            else if(roleName == "WaterPlant Admin"){
                for(WaterTreatmentOrg cust : this.system.getWaterTreatementirectory().returnAllWaterTreatmentBusinesses()){
//                    System.out.println(cust.getHospitalAdmin());
                    Object[] row = new Object[6];
                    row[0] = cust.getBusinessAdmin();
                    row[1] = cust.getBusinessAdmin().getUserName();
                    row[2] = cust.getBusinessAdmin().getUserPassword();
                    row[3] = cust.getBusinessAdmin().getAddress();
                    row[4] = cust.getBusinessAdmin().getPhoneNumber();
                    row[5] = cust.getBusinessName();
                    model.addRow(row);
                    }
            }
        }catch(NullPointerException e){
            System.out.println("Null pointer exception occured as there is no hospital Admin data");
        }
    }

}
