/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Hospital.Hospital;
import Business.Hospital.HospitalAdmin;
import Business.NGO.NGOAdmin;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nithin Bharadwaj
 */
public class ManageNgoAdmin extends javax.swing.JPanel {

    /**
     * Creates new form UpdateCustomerDetails
     */
    JPanel userProcessContainer;
    EcoSystem system;
    
    public ManageNgoAdmin(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.system = system;
        this.userProcessContainer = userProcessContainer;
        this.populateTable();
//        txtName.setEditable(false);
//        txtUsername.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomerDetails = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtUsername = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        lbPassword = new javax.swing.JLabel();
        lbName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lbUsername = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtpassword = new javax.swing.JPasswordField();
        lbPassword1 = new javax.swing.JLabel();
        lbPassword2 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(246, 252, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Manage NGO Admin Details");
        add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 36, 420, -1));

        tblCustomerDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Name", "UserName", "Password", "Address", "PhoneNumber", "Organization Name"
            }
        ));
        jScrollPane1.setViewportView(tblCustomerDetails);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 118, 640, 96));

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 232, 96, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(593, 264, 96, -1));

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 264, 159, -1));

        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 422, -1, -1));

        lbPassword.setText("Password :");
        add(lbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 307, -1, -1));

        lbName.setText("Name :");
        add(lbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 237, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 232, 159, -1));

        lbUsername.setText("Username :");
        add(lbUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 269, -1, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 36, 58, 54));
        add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 302, 159, -1));

        lbPassword1.setText("Address :");
        add(lbPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 345, -1, -1));

        lbPassword2.setText("Phone Number :");
        add(lbPassword2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 389, -1, -1));
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 340, 159, -1));
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 384, 159, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/slogan-for-ngo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        Component[] comps = this.userProcessContainer.getComponents();
        for(Component comp : comps){
            if(comp instanceof SystemAdminWorkAreaJPanel){
                SystemAdminWorkAreaJPanel systemAdminWorkAreaJPanel= (SystemAdminWorkAreaJPanel) comp;
                systemAdminWorkAreaJPanel.populateTree();
            }
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCustomerDetails.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        NGOAdmin selectedCustomer = (NGOAdmin)model.getValueAt(selectedRowIndex, 0);
        String name = txtName.getText();
        String userName = txtUsername.getText();
        String password = txtpassword.getText();

        
        ArrayList<NGOAdmin> restos = system.getNGODirectory().returnAdminDetails();
        for(NGOAdmin r: restos)
        {
            if(r.getName().equals(selectedCustomer.getName()))
            {
                r.setName(name);
                r.returnUserAccount().setUsername(userName);
                r.returnUserAccount().setPassword(password);
                r.setUserName(userName);
                r.setUserPassword(password);
                r.setPhoneNumber(Long.parseLong(txtPhoneNumber.getText()));
                r.setAddress(txtAddress.getText());
                break;
            }
            
        }
        this.system.setNGODirectory(restos, 
                this.system.getNGODirectory().returnEmployeeDetails());
        JOptionPane.showMessageDialog(this, "Updated Successfully");
        
        txtName.setText("");txtUsername.setText("");txtpassword.setText("");
        txtAddress.setText("");txtPhoneNumber.setText("");
        populateTable();
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCustomerDetails.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to View");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        NGOAdmin selectedCustomer = (NGOAdmin)model.getValueAt(selectedRowIndex, 0);
        txtName.setText("");
        txtName.setText(selectedCustomer.getName());
        txtUsername.setText("");
        txtUsername.setText(selectedCustomer.getUserName());
        txtpassword.setText("");
        txtpassword.setText(selectedCustomer.getUserPassword());
        txtAddress.setText("");
        txtAddress.setText(selectedCustomer.getAddress());
        txtPhoneNumber.setText("");
        txtPhoneNumber.setText(String.valueOf(selectedCustomer.getPhoneNumber()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblCustomerDetails.getSelectedRow();
        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        NGOAdmin selectedCustomer = (NGOAdmin)model.getValueAt(selectedRowIndex, 0);
        // First delete the customer from employee
        this.system.getEmployeeDirectory().deleteEmployee(selectedCustomer.getName());
        // And thne delete the userAccount
        this.system.getUserAccountDirectory().deleteUserAccount(
                this.system.getNGODirectory().returnAdminDetails().
                        get(selectedRowIndex).returnUserAccount()
        );
        // finally delete the user from customer directory
        Iterator<NGOAdmin> itr = this.system.getNGODirectory().returnAdminDetails().iterator();
        while (itr.hasNext()) {
          NGOAdmin selectedAdmin = itr.next();
          if (selectedAdmin.getName().equals(selectedCustomer.getName())) {
            itr.remove();
          }
        }
       
        this.populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPassword;
    private javax.swing.JLabel lbPassword1;
    private javax.swing.JLabel lbPassword2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbUsername;
    private javax.swing.JTable tblCustomerDetails;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables

    private void populateTable(){
        System.out.println("Inside method to populate Customer table");
        DefaultTableModel model = (DefaultTableModel) tblCustomerDetails.getModel();
        model.setRowCount(0);
        try{
            for(NGOAdmin cust : this.system.getNGODirectory().returnAdminDetails()){

            Object[] row = new Object[6];
            row[0] = cust;
            row[1] = cust.getUserName();
            row[2] = cust.getUserPassword();
            row[3] = cust.getAddress();
            row[4] = cust.getPhoneNumber();
            row[5] = cust.getBusinessName();
            model.addRow(row);
            }
        }catch(NullPointerException e){
            System.out.println("Null pointer exception occured as there is no hospital Admin data");
        }
    }

}
