/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.DeliveryMan.DeliveryMan;
import Business.EcoSystem;

import Business.Organization;
import Business.OxygenPlant.OxygenPlant;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author MyPC1
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
//        populateTree();
    }
    
    public void populateTree(){
//        DefaultTreeModel model=(DefaultTreeModel)jTree.getModel();
        // Add the code for draw your system structure shown by JTree
        DefaultMutableTreeNode networks=new DefaultMutableTreeNode("SystemAdmin");
//        DefaultMutableTreeNode root=(DefaultMutableTreeNode)model.getRoot();
//        root.removeAllChildren();
//        root.insert(networks, 0);

        ArrayList<Customer> customerDir= this.ecosystem.getCustomerDirectory().returnCustomerDetails();
        ArrayList<DeliveryMan> deliveryDir = ecosystem.getDeliveryManDirectory().returnDeliveryAgentDetails();
        ArrayList<OxygenPlant> restaurantDir = ecosystem.getOxygenPlantDirectory().returnAllOxygenPlants();

        Customer customer;
        DeliveryMan deliveryMan;
        OxygenPlant restaurant;

        DefaultMutableTreeNode customerListNode = new DefaultMutableTreeNode("Customer");
        DefaultMutableTreeNode deliveryManListNode = new DefaultMutableTreeNode("Delivery");
        DefaultMutableTreeNode restaurantListNode = new DefaultMutableTreeNode("Restaurant");
        networks.insert(customerListNode, 0);
        networks.insert(deliveryManListNode, 1);
        networks.insert(restaurantListNode, 2);

        DefaultMutableTreeNode networkNode;
        DefaultMutableTreeNode enterpriseNode;
        DefaultMutableTreeNode organizationNode;

        for(int i=0;i<customerDir.size();i++){
        customer=customerDir.get(i);
        networkNode=new DefaultMutableTreeNode(customer.getName());
        customerListNode.insert(networkNode, i);

        }
        for(int j=0; j<deliveryDir.size();j++){
        deliveryMan= deliveryDir.get(j);
        enterpriseNode=new DefaultMutableTreeNode(deliveryMan.getName());
        deliveryManListNode.insert(enterpriseNode, j);
        }

        for(int k=0;k<restaurantDir.size();k++){
        restaurant=restaurantDir.get(k);
        organizationNode=new DefaultMutableTreeNode(restaurant.getOxygenPlantName());
        restaurantListNode.insert(organizationNode, k);
        }

//        model.reload();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblSelectedNode = new javax.swing.JLabel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageOxygenPlants = new javax.swing.JButton();
        btnManageDeliveryMan = new javax.swing.JButton();
        btnNewUser = new javax.swing.JButton();
        btnManageHospitalAdmin = new javax.swing.JButton();
        btnManageHospitalEmployee = new javax.swing.JButton();
        btnManageSalesManager = new javax.swing.JButton();
        btnManageSalesExecutive = new javax.swing.JButton();
        btnManageNGOAdmin = new javax.swing.JButton();
        btnManageNGOEmployee = new javax.swing.JButton();
        btnManageBusinessAdmin = new javax.swing.JButton();
        btnManageBusinessEmployee = new javax.swing.JButton();
        btnPendingApproval = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(246, 252, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selected Node:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 25, 0, -1));

        lblSelectedNode.setText("<View_selected_node>");
        jPanel2.add(lblSelectedNode, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 25, 2, -1));

        btnManageNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_customer_20px_2.png"))); // NOI18N
        btnManageNetwork.setText("Manage All Consumers");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 260, 40));

        btnManageOxygenPlants.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_restaurant_20px.png"))); // NOI18N
        btnManageOxygenPlants.setText("Manage Oxygen Plants");
        btnManageOxygenPlants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOxygenPlantsActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageOxygenPlants, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 190, -1));

        btnManageDeliveryMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Delivery.png"))); // NOI18N
        btnManageDeliveryMan.setText("Manage Deliveryman");
        btnManageDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDeliveryManActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageDeliveryMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 190, -1));

        btnNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_user_20px.png"))); // NOI18N
        btnNewUser.setText("Create New User");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 190, -1));

        btnManageHospitalAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Hospital.png"))); // NOI18N
        btnManageHospitalAdmin.setText("Manage Hospital Admin");
        btnManageHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageHospitalAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 230, 200, 31));

        btnManageHospitalEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Hospital2.png"))); // NOI18N
        btnManageHospitalEmployee.setText("Manage Hospital Employee");
        btnManageHospitalEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageHospitalEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 270, 200, 29));

        btnManageSalesManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ManagerSalesTwo.png"))); // NOI18N
        btnManageSalesManager.setText("Manage Sales Manager");
        btnManageSalesManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSalesManagerActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageSalesManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 230, 200, 31));

        btnManageSalesExecutive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ManagerSales.png"))); // NOI18N
        btnManageSalesExecutive.setText("Manage Sales Executive");
        btnManageSalesExecutive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSalesExecutiveActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageSalesExecutive, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 270, 200, 31));

        btnManageNGOAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NGOONE.png"))); // NOI18N
        btnManageNGOAdmin.setText("Manage NGO Administrator");
        btnManageNGOAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNGOAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNGOAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, 31));

        btnManageNGOEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/NGOONE.png"))); // NOI18N
        btnManageNGOEmployee.setText("Manage NGO Employee");
        btnManageNGOEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNGOEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageNGOEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 200, 29));

        btnManageBusinessAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BusinessTwo.png"))); // NOI18N
        btnManageBusinessAdmin.setText("Manage Bussiness Admin");
        btnManageBusinessAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBusinessAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageBusinessAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 230, 200, 31));

        btnManageBusinessEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/BusinessTwo.png"))); // NOI18N
        btnManageBusinessEmployee.setText("Manage Bussiness Assitant");
        btnManageBusinessEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBusinessEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(btnManageBusinessEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 200, 29));

        btnPendingApproval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_user_20px.png"))); // NOI18N
        btnPendingApproval.setText("Manage Pending Account Approvals");
        btnPendingApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendingApprovalActionPerformed(evt);
            }
        });
        jPanel2.add(btnPendingApproval, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 45, -1, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/g2i.gif"))); // NOI18N
        jLabel2.setText("company_gif");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 1490, 730));

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed

        UpdateCustomerDetails customerObj = new UpdateCustomerDetails(userProcessContainer,
                                                ecosystem);
        userProcessContainer.add("CustomerDashboard", customerObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageOxygenPlantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOxygenPlantsActionPerformed
        ManageRestaurantDetails restaurantDetailsObj = new ManageRestaurantDetails(
                                    userProcessContainer, ecosystem);
        
        userProcessContainer.add("RestaurantDashboard", restaurantDetailsObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageOxygenPlantsActionPerformed

    private void btnManageDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDeliveryManActionPerformed
       ManageDeliveryUsers deliveryUsersObj = new ManageDeliveryUsers(
                                    userProcessContainer, ecosystem);
        
        userProcessContainer.add("DeliveryUserDashboard", deliveryUsersObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageDeliveryManActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        // TODO add your handling code here:
        CreateUser createUserObj = new CreateUser(userProcessContainer,
                                                ecosystem);
        userProcessContainer.add("CreateUser", createUserObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnManageHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalAdminActionPerformed
        // TODO add your handling code here:
        ManageHospitalAdmin hospitalAdminObj = new ManageHospitalAdmin(userProcessContainer,
                                                ecosystem);
        userProcessContainer.add("HospitalAdminDashboard", hospitalAdminObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHospitalAdminActionPerformed

    private void btnManageHospitalEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalEmployeeActionPerformed
        // TODO add your handling code here:
        ManageHospitalEmployee hospitalEmpObj = new ManageHospitalEmployee(userProcessContainer,
                                                ecosystem);
        userProcessContainer.add("HospitalEmployeeDashboard", hospitalEmpObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageHospitalEmployeeActionPerformed

    private void btnManageSalesManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSalesManagerActionPerformed
        // TODO add your handling code here:
        ManageSalesManager salesManagerObj = new ManageSalesManager(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("SalesManagerDashboard", salesManagerObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSalesManagerActionPerformed

    private void btnManageSalesExecutiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSalesExecutiveActionPerformed
        // TODO add your handling code here:
        ManageSalesExecutiveDetails salesExecutiveObj = new ManageSalesExecutiveDetails(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("SalesExecutiveDashboard", salesExecutiveObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);       
        
    }//GEN-LAST:event_btnManageSalesExecutiveActionPerformed

    private void btnManageNGOEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNGOEmployeeActionPerformed
        // TODO add your handling code here:
        
        ManageNgoEmployee ngoEmployeeObj = new ManageNgoEmployee(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("NgoEmployeeDashboard", ngoEmployeeObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNGOEmployeeActionPerformed

    private void btnManageBusinessAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBusinessAdminActionPerformed
        // TODO add your handling code here:
        
        ManageBussinessAdmin bussinessAdminObj = new ManageBussinessAdmin(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("BusinessAdminDashboard", bussinessAdminObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageBusinessAdminActionPerformed

    private void btnManageBusinessEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBusinessEmployeeActionPerformed
        // TODO add your handling code here:
        
        ManageBusinessAssistant bussinessEmployeeObj = new ManageBusinessAssistant(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("BusinessAdminDashboard", bussinessEmployeeObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageBusinessEmployeeActionPerformed

    private void btnManageNGOAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNGOAdminActionPerformed
        // TODO add your handling code here:
        ManageNgoAdmin ngoAdminObj = new ManageNgoAdmin(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("NgoAdminDashboard", ngoAdminObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageNGOAdminActionPerformed

    private void btnPendingApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendingApprovalActionPerformed
        // TODO add your handling code here:
        ManagePendingAccountApprovals managePendingAccObj = new ManagePendingAccountApprovals(userProcessContainer,
                                             ecosystem);
        userProcessContainer.add("AccountPendingApprovalsPanel", managePendingAccObj);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPendingApprovalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageBusinessAdmin;
    private javax.swing.JButton btnManageBusinessEmployee;
    private javax.swing.JButton btnManageDeliveryMan;
    private javax.swing.JButton btnManageHospitalAdmin;
    private javax.swing.JButton btnManageHospitalEmployee;
    private javax.swing.JButton btnManageNGOAdmin;
    private javax.swing.JButton btnManageNGOEmployee;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnManageOxygenPlants;
    private javax.swing.JButton btnManageSalesExecutive;
    private javax.swing.JButton btnManageSalesManager;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnPendingApproval;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel lblSelectedNode;
    // End of variables declaration//GEN-END:variables
}
